<html><head>
	<title>Dzedia Breeze</title>
	<style>
		/* Global styles */
		h1{
			text-align: center;
		}
		body {
			font-family: Arial, sans-serif;
			margin: 0;
			padding: 0;
		}
		h1, h2, h3, h4, h5, h6 {
			margin: 0;
		}
		header {
			background-color: #333;
			color: #fff;
			padding: 20px;
			
		}
		nav ul {
			list-style: none;
			margin: 0;
			padding: 0;
		}
		nav li {
			display: inline-block;
			margin-right: 20px;
		}
		nav a {
			color: #fff;
			text-decoration: none;
			padding: 5px;
			transition: all 0.3s ease-in-out;
		}
		nav a:hover {
			background-color: #fff;
			color: #333;
		}
		main {
			padding: 20px;
			max-width: 1200px;
			margin: 0 auto;
		}
		section {
			margin-bottom: 40px;
		}
		h2 {
			font-size: 2em;
			margin-bottom: 10px;
		}
		p {
			margin-bottom: 10px;
		}
		ul {
			margin-left: 20px;
			margin-bottom: 10px;
		}
		label {
			display: block;
			margin-bottom: 10px;
		}
		input[type="text"], input[type="email"], textarea {
			display: block;
			width: 100%;
			padding: 10px;
			margin-bottom: 10px;
			border: 1px solid #ccc;
			border-radius: 3px;
			font-size: 1em;
			color: #333;
			box-sizing: border-box;
		}
		input[type="submit"] {
			background-color: #333;
			color: #fff;
			padding: 10px 20px;
			border: none;
			border-radius: 3px;
			font-size: 1em;
			cursor: pointer;
		}
		input[type="submit"]:hover {
			background-color: #fff;
			color: #333;
		}
		footer {
			background-color: #333;
			color: #fff;
			padding: 20px;
			text-align: center;
		}
		img {
			position: absolute;
			bottom: -681px;
			left: 3px;
			width: 85px; /* Change this value to adjust the size of your logo */
		}
		.imagetwo {
			position: absolute;
			bottom: -681px;
			left: 1062px;
			width: 85px; /* Change this value to adjust the size of your logo */
		}

	</style>
</head>
		<body><img src="H:\Pictures\Dezedia\Light.jpg" alt="Your Logo">
		<img class="imagetwo" src="H:\Pictures\Dezedia\Light.jpg" alt="Your Logo">

	<header>
		<h1>Welcome to Dzedia Breeze Offical Website</h1>
		<nav>
			<ul>
				<li><a href="#home">Home</a></li>
				<li><a href="#about">About</a></li>
				<li><a href="#services">Services</a></li>
				<li><a href="#contact">Contact</a></li>
			</ul>
		</nav>
	</header>
	<main>
		<section id="home">
			<h2>Home</h2>
			<p>Welcome to Dzedia Breeze Offical Website, ENJOY !</p>
		</section>
		<section id="about">
			<h2><br>About</h2>
			<p>Learn more about us and our business.<br> This is the inventors of Dzedia Breeze's idea: <br> </p><li>Yasmine Abba &amp; Mohamed Abba</li><p></p>
		</section>
		<section id="services">
			<h2><br>Services</h2>
			<ul>
				<li>You Can Learn English Easly With The Help Of The Teachers Or The Inventors.</li>
				<li>We Can Give You Some Tasks or Exercices For You To Enhance Your English Language Vocabulary</li>
				<li>You Can Contact Us For Help Or Any Quesstion, We Are Always Available For Help. (more contact links below)</li>
			</ul>
		</section>
		<section id="contact">
			<h2><br>Contact</h2>
			<form>
				<label for="name">Name:</label>
				<input type="text" id="name" name="name"><br><br>
				<label for="email">Email:</label>
				<input type="email" id="email" name="email"><br><br>
				<label for="message">Message:</label>
				<textarea id="message" name="message"></textarea><br><br>
				<input type="submit" value="Send">
			</form>
		</section>
	</main>
	<footer>
		<p>© 2023 copyright.</p>
	</footer>

</body></html>
